language: php

php:
    - '7.0'
    - '7.1'
    - '7.2'

before_script:
 - cd include
 - composer install
 - cd ..

script:
 - phpunit include/modules/tests/*.php
 - ./validate.sh
 - npm install yarn
 - yarn install
 - yarn test
 - yarn run build
 - yarn run lint 

node_js:
 - "7"
 - "8"
