language: php

php:
    - '7.0'
    - '7.1'
    - nightly

before_script:
 - cd include
 - composer install
 - cd ..

script:
 - phpunit include/modules/tests/*.php
 - npm install yarn
 - yarn install
 - yarn test
 - tsc

node_js:
 - "7"
 - "8"
